Занятие 2: Объекты
js-tasks-ru/jsbasic-20230428_adievrinat pull request #3
Opened 2023-05-09 08:22 UTC by adievrinat

https://learn.javascript.ru/taskbook/jsbasic-20230428/workspace/2-module

2023-05-09 08:23 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-09 08:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-10 10:10 UTC, SinimaWath requested changes

2023-05-10 10:10 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  if (typeof salaries !== 'object' || salaries === null || Array.isArray(salaries)) {
nit: Проверки: `Array.isArray(salaries)`, должно хватить в этом случае

2023-05-10 10:28 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-10 10:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-10 12:41 UTC, adievrinat commented on 2-module/1-task/index.js
> +  if (typeof salaries !== 'object' || salaries === null || Array.isArray(salaries)) {
Исправил

2023-05-12 07:18 UTC, SinimaWath approved these changes

2023-05-12 07:19 UTC, merged