Занятие 4: Знакомство с DOM. Выделите ячейки по диагонали
js-tasks-ru/jsbasic-20230428_adievrinat pull request #6
Opened 2023-05-18 06:54 UTC by adievrinat

https://learn.javascript.ru/taskbook/jsbasic-20230428/workspace/4-module

2023-05-18 06:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-18 14:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-18 14:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-18 15:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-18 15:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-18 15:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-18 16:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-18 18:48 UTC, SinimaWath requested changes

2023-05-18 18:48 UTC, SinimaWath commented on 4-module/3-task/index.js
> +      const isDataAvailable = !row.cells[statusIndex].getAttribute('data-available').localeCompare('true');
это data аттрибут, поэтому используй здесь и в других местах свойство: `dataset.available`

2023-05-18 18:48 UTC, SinimaWath commented on 4-module/3-task/index.js
> +      const isDataAvailable = !row.cells[statusIndex].getAttribute('data-available').localeCompare('true');
Не уверен что здесь нужен localComapare

2023-05-19 01:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-19 01:03 UTC, adievrinat commented on 4-module/3-task/index.js
> +      const isDataAvailable = !row.cells[statusIndex].getAttribute('data-available').localeCompare('true');
Исправил

2023-05-20 08:36 UTC, SinimaWath approved these changes

2023-05-20 08:37 UTC, merged